sudo: false
language: java
script: ./mvnw clean verify
jdk:
  - openjdk7
  - openjdk8
  - openjdk9
after_success:
  - if [ $SONATYPE_USERNAME ] && [ -z $TRAVIS_TAG ] && [ $TRAVIS_PULL_REQUEST == false ]; then
      ./mvnw clean deploy --settings .travis/settings.xml;
    fi;
branches:
  only:
  - master
  - 2.0
