sudo: false
language: java
script: mvn clean verify
jdk:
  - oraclejdk8
after_success:
  - if [ $SONATYPE_USERNAME ] && [ -z "$TRAVIS_TAG" ] && [ ! "$TRAVIS_PULL_REQUEST" ]; then
      mvn clean deploy --settings .travis/settings.xml;
    fi;
